version: '3.9'
services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "2580:2580"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:2580"